# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, unique=True)),
                ('eth0', models.GenericIPAddressField(unique=True)),
                ('eth1', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
