# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160514_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth0',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
